sudo: false
language: node_js
node_js:
    - "6.10.3"
notifications:
  email: false
before_install:
    - export TZ=America/Los_Angeles
script:
    npm test -- --coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
